# Generated by Django 4.1.3 on 2022-11-26 09:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
