# Generated by Django 4.1.3 on 2022-11-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='amount_to_raise',
            new_name='event_amount',
        ),
        migrations.AddField(
            model_name='events',
            name='amount_donated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
