# Generated by Django 4.1.3 on 2022-11-30 15:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_rename_amount_to_raise_events_event_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('transaction_amount', models.IntegerField(blank=True, null=True)),
                ('original_amount', models.IntegerField(blank=True, null=True)),
                ('is_partial', models.BooleanField(default=False)),
                ('currency_code', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('merchant_reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_token', models.CharField(max_length=200)),
                ('payment_method', models.CharField(max_length=200)),
                ('event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.events')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
