# Generated by Django 4.1.3 on 2022-12-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='event_id',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
